"""
PA#18 Sender Privacy Brute-Force Evidence.

The PDF requires:
"For small parameters, attempt a brute-force decryption and show it requires solving DLP or factoring."

In our OT (PA#18), the Sender Privacy relies on the indistinguishability of the 
two public keys (pk0, pk1) generated by the receiver. One has a known discrete log (trapdoor), 
the other does not (it's a random group element).
To "break" sender privacy, the sender must distinguish which pk has a trapdoor.
To do this directly, the sender must compute the discrete logarithm (DLP) of pk0.y and pk1.y.
We will demonstrate this brute-force attack on a tiny group and show that it effectively solves the DLP.
"""

import os, sys, json, time
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "../../docs/results")
os.makedirs(OUTPUT_DIR, exist_ok=True)

def brute_force_dlp(g: int, y: int, p: int, q: int) -> int | None:
    """Solve g^x = y mod p by trying all x in Z_q."""
    for x in range(q):
        if pow(g, x, p) == y:
            return x
    return None

def run_pa18_sender_privacy_demo():
    from src.pa18_ot.ot import OTReceiverStep1
    from src.foundations.dlp_group import DEMO_PARAMS # tiny group: p=23, q=11, g=4

    print(f"\n{'='*70}")
    print("PA#18 Sender Privacy — Security Argument & Evidence")
    print(f"{'='*70}")
    
    b = 1  # Receiver wants message m_1
    pk0, pk1, state = OTReceiverStep1(b, DEMO_PARAMS)
    
    print(f"1. Receiver choice b = {b}")
    print(f"2. Receiver generates pk{b} honestly with a known trapdoor (sk).")
    print(f"3. Receiver constructs pk{1-b} as C / pk{b}. By construction, pk{1-b} has no associated secret key.")
    
    print(f"\nSender sees the following keys for group (p={DEMO_PARAMS.p}, q={DEMO_PARAMS.q}, g={DEMO_PARAMS.g}):")
    print(f"  pk0 = {pk0.y}")
    print(f"  pk1 = {pk1.y}")
    
    print("\nEvidence Structure & Security Argument:")
    print("  - Both keys are drawn from the same group and are format-identical.")
    print("  - A sender seeing (pk0, pk1) cannot tell which is real vs random without solving DDH.")
    print("  - Because C is a valid generator, C/pk_b is a random group element computationally indistinguishable from pk_b.")
    
    print("\n--- Brute-Force Check (Illustrative Only) ---")
    # Try breaking pk0
    t0 = time.perf_counter()
    x0 = brute_force_dlp(DEMO_PARAMS.g, pk0.y, DEMO_PARAMS.p, DEMO_PARAMS.q)
    t_pk0 = (time.perf_counter() - t0) * 1000
    
    # Try breaking pk1
    t0 = time.perf_counter()
    x1 = brute_force_dlp(DEMO_PARAMS.g, pk1.y, DEMO_PARAMS.p, DEMO_PARAMS.q)
    t_pk1 = (time.perf_counter() - t0) * 1000
    
    print(f"  Brute-forcing pk0: x = {x0} (took {t_pk0:.2f} ms)")
    print(f"  Brute-forcing pk1: x = {x1} (took {t_pk1:.2f} ms)")
    print("  Note: The brute-force DLP success on tiny parameters is expected and is noted as illustrative only.")
    print("  Real security holds under full-size DDH-hard parameters where this operation is infeasible.")

    results = {
        "group": {"p": DEMO_PARAMS.p, "q": DEMO_PARAMS.q, "g": DEMO_PARAMS.g},
        "receiver_choice": b,
        "pk_b_honest_with_trapdoor": pk1.y,
        "pk_1_minus_b_random": pk0.y,
        "brute_force_dlp_pk0": x0,
        "brute_force_dlp_pk1": x1,
        "conclusion": "A sender seeing (pk0, pk1) cannot tell which is real vs random without solving DDH. Brute-force success on tiny parameters is illustrative only."
    }

    out = os.path.join(OUTPUT_DIR, "pa18_sender_privacy.json")
    with open(out, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to {out}")
    return results

if __name__ == "__main__":
    run_pa18_sender_privacy_demo()
